include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - empty_catches
    - package_api_docs
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures

analyzer:
  exclude:
    - lib/generated/**
  language:
    strict-casts: true
    strict-raw-types: true
