name: backend_service
description: Backend service for the strategy simulation game
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^1.4.0
  path: ^1.8.3
  args: ^2.4.2
  uuid: ^3.0.7
  equatable: ^2.0.5
  riverpod: ^2.3.6  # Nicht-Flutter Version von Riverpod
  game_core:
    path: ../packages/game_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
